<?php

namespace App\Filament\Resources\LegacyMigrationPlans\Tables;

use App\Enums\LegacyMigrationPlanStatus;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;

class LegacyMigrationPlansTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('batch.source_filename')->label('Batch'),
                TextColumn::make('status')->label('Status')->badge(),
                TextColumn::make('plan_fingerprint')->label('Fingerprint')->copyable()->limit(12),
                TextColumn::make('generatedBy.name')->label('Generated By'),
                TextColumn::make('generated_at')->label('Generated')->dateTime()->sortable(),
            ])
            ->filters([
                SelectFilter::make('status')->options(LegacyMigrationPlanStatus::class),
            ])
            ->defaultSort('generated_at', 'desc');
    }
}
