<?php

namespace App\Filament\Resources\LegacyMigrationPlans\Schemas;

use App\Models\LegacyMigrationPlan;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class LegacyMigrationPlanInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make('Plan')->columns(3)->schema([
                TextEntry::make('status')->label('Status')->badge(),
                TextEntry::make('plan_fingerprint')->label('Plan Fingerprint')->copyable(),
                TextEntry::make('source_fingerprint')->label('Source Fingerprint')->copyable()->limit(16),
                TextEntry::make('audit_fingerprint')->label('Audit Fingerprint')->copyable()->limit(16),
                TextEntry::make('generatedBy.name')->label('Generated By'),
                TextEntry::make('generated_at')->label('Generated')->dateTime(),
            ]),
            Section::make('Summary')->schema([
                TextEntry::make('summary_totals')->label('Totals')
                    ->state(fn (LegacyMigrationPlan $record): string => json_encode($record->summary_totals, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)),
            ]),
        ]);
    }
}
